// Adapter: a Polygraph trace (+ optional findings.json) → viz-model `trace`
// section (spec §4.3). Two trace shapes are accepted:
//   • rich  — captured execution: { pre, action, data, post } per line (ndjson)
//   • simple — raw ops:           { op, actor, ... } per line
// Structure (steps, redelivered no-ops, the violating step) is derived; the
// narrative (violation title/detail, callout prose) comes from annotations or
// a findings reject-reason, else sensible defaults.

const cap = (s) => (s ? String(s)[0].toUpperCase() + String(s).slice(1) : s);
const deepEqual = (a, b) => JSON.stringify(a) === JSON.stringify(b);

// Parse ndjson text (or accept an already-parsed array of records).
export function parseTrace(input) {
  if (Array.isArray(input)) return input;
  return String(input)
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => JSON.parse(l));
}

function normalize(rec) {
  if (rec.action != null) {
    return { action: rec.action, actor: rec.data?.actor, pre: rec.pre, post: rec.post };
  }
  return { action: rec.op, actor: rec.actor, pre: undefined, post: undefined };
}

// Reason token out of a classification like "rejected(duplicate-approver)".
export function rejectReason(classification) {
  const m = /rejected\(([^)]+)\)/.exec(String(classification ?? ''));
  return m ? m[1] : null;
}

/**
 * Build a viz-model `trace` from trace records. opts:
 *   { annotations?, violationIndex?, reason? }
 * violationIndex marks the violating step (defaults to the last step); reason
 * feeds the default violation detail.
 */
export function adaptCounterexample(input, { annotations = {}, violationIndex = null, reason = null } = {}) {
  const records = parseTrace(input).map(normalize);
  if (!records.length) throw new Error('counterexample adapter: trace has no steps');
  const a = annotations;

  const steps = records.map((r, i) => {
    const label = r.actor ? `${r.action}(${cap(r.actor)})` : `${r.action}()`;
    let kind = 'normal';
    // rich no-op (post == pre) = a redelivered / rejected step.
    if (r.pre !== undefined && r.post !== undefined && deepEqual(r.pre, r.post)) kind = 'redelivered';
    // simple: a repeat of the previous op+actor is a redelivery.
    else if (r.pre === undefined && i > 0 &&
      records[i - 1].action === r.action && records[i - 1].actor === r.actor) kind = 'redelivered';
    const step = { label, kind };
    if (kind === 'redelivered') step.annotation = '(redelivered)';
    return step;
  });

  const vIdx = a.violationIndex ?? violationIndex ?? steps.length - 1;
  if (steps[vIdx]) {
    const anno = a.violationAnnotation ?? steps[vIdx].annotation;
    steps[vIdx] = { ...steps[vIdx], kind: 'violation' };
    if (anno != null) steps[vIdx].annotation = anno;
    else delete steps[vIdx].annotation;
  }

  const detailFromReason = reason
    ? `The gate rejected step ${vIdx} with reason "${reason}" — the reachable path that exposes it.`
    : 'The gate reached a state that violates a declared invariant.';

  const violation = {
    title: a.violationTitle ?? (a.invariantId ? `${a.invariantId} VIOLATED` : 'Invariant violated'),
    detail: a.violationDetail ?? detailFromReason
  };
  if (a.invariantId) violation.invariantId = a.invariantId;

  return {
    kicker: a.kicker ?? 'THE BUG IT CAUGHT',
    title: a.title ?? 'The gate wrote its own reproduction',
    subtitle: a.subtitle ?? 'The gate explored the reachable states and handed back the shortest sequence that reaches the violation.',
    steps,
    violation,
    callout: a.callout ?? {
      title: `This ${steps.length}-step path was generated by the gate — not by hand.`,
      body: 'The gate explored the reachable states, found the hole, and returned the shortest sequence that reaches it.',
      cleanPasses: true
    }
  };
}
