// GENERATED by polynv from intent-ledger.json — do not edit by hand; revise via `polynv record --disposition modify`.
// 18 confirmed rule(s) (+ 2 emission confirmed rule(s) NOT compiled here — see intent-report).
const canon = (v) => {
  if (Array.isArray(v)) return '[' + v.map(canon).join(',') + ']';
  if (v && typeof v === 'object')
    return '{' + Object.keys(v).sort().map((k) => JSON.stringify(k) + ':' + canon(v[k])).join(',') + '}';
  return JSON.stringify(v) ?? 'undefined';
};
const sameOn = (keys) => (a, b) => keys.every((k) => canon(a[k]) === canon(b[k]));

export const stateInvariants = [
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:34.255Z — ledger record: range:fulfillments
    name: "range:fulfillments",
    pred: (s) => typeof s["fulfillments"] === 'number' && s["fulfillments"] >= 0 && s["fulfillments"] <= 2,
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:36.229Z — ledger record: range:shipmentsDelivered
    name: "range:shipmentsDelivered",
    pred: (s) => typeof s["shipmentsDelivered"] === 'number' && s["shipmentsDelivered"] >= 0 && s["shipmentsDelivered"] <= 2,
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:38.219Z — ledger record: range:shipmentsFailed
    name: "range:shipmentsFailed",
    pred: (s) => typeof s["shipmentsFailed"] === 'number' && s["shipmentsFailed"] >= 0 && s["shipmentsFailed"] <= 2,
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:40.191Z — ledger record: nonneg:totalCents
    name: "nonneg:totalCents",
    pred: (s) => typeof s["totalCents"] === 'number' && s["totalCents"] >= 0,
  },
];

export const transitionInvariants = [
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:17.239Z — ledger record: terminal-absorbing:completed
    name: "terminal-absorbing:completed",
    pred: (pre, action, data, post) => pre["orderState"] !== "completed" || sameOn(["orderState","fulfillments","shipmentsDelivered","shipmentsFailed","totalCents","txId","cancelReason"])(pre, post),
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:19.340Z — ledger record: terminal-absorbing:partiallyDelivered
    name: "terminal-absorbing:partiallyDelivered",
    pred: (pre, action, data, post) => pre["orderState"] !== "partiallyDelivered" || sameOn(["orderState","fulfillments","shipmentsDelivered","shipmentsFailed","totalCents","txId","cancelReason"])(pre, post),
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:21.436Z — ledger record: terminal-absorbing:rejected
    name: "terminal-absorbing:rejected",
    pred: (pre, action, data, post) => pre["orderState"] !== "rejected" || sameOn(["orderState","fulfillments","shipmentsDelivered","shipmentsFailed","totalCents","txId","cancelReason"])(pre, post),
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:23.523Z — ledger record: terminal-absorbing:paymentFailed
    name: "terminal-absorbing:paymentFailed",
    pred: (pre, action, data, post) => pre["orderState"] !== "paymentFailed" || sameOn(["orderState","fulfillments","shipmentsDelivered","shipmentsFailed","totalCents","txId","cancelReason"])(pre, post),
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:25.438Z — ledger record: terminal-absorbing:cancelled
    name: "terminal-absorbing:cancelled",
    pred: (pre, action, data, post) => pre["orderState"] !== "cancelled" || sameOn(["orderState","fulfillments","shipmentsDelivered","shipmentsFailed","totalCents","txId","cancelReason"])(pre, post),
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:42.283Z — ledger record: monotone:shipmentsDelivered
    name: "monotone:shipmentsDelivered",
    pred: (pre, action, data, post) => post["shipmentsDelivered"] >= pre["shipmentsDelivered"],
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:44.317Z — ledger record: monotone:shipmentsFailed
    name: "monotone:shipmentsFailed",
    pred: (pre, action, data, post) => post["shipmentsFailed"] >= pre["shipmentsFailed"],
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:27.559Z — ledger record: set-once:txId
    name: "set-once:txId",
    pred: (pre, action, data, post) => pre["txId"] === "" || post["txId"] === pre["txId"],
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:46.468Z — ledger record: set-once:cancelReason
    name: "set-once:cancelReason",
    pred: (pre, action, data, post) => pre["cancelReason"] === "" || post["cancelReason"] === pre["cancelReason"],
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:29.561Z — ledger record: reject-in-state:cancel-blocked-while-charging
    name: "reject-in-state:cancel-blocked-while-charging",
    pred: (pre, action, data, post) => !(["CANCEL"].includes(action) && pre["orderState"] === "charging") || sameOn(["orderState","fulfillments","shipmentsDelivered","shipmentsFailed","totalCents","txId","cancelReason"])(pre, post),
  },
  { // elicited-by: template — confirmed by jdubray 2026-07-18T13:40:31.760Z — ledger record: reject-in-state:fulfillment-in-progress
    name: "reject-in-state:fulfillment-in-progress",
    pred: (pre, action, data, post) => !(["CANCEL"].includes(action) && pre["orderState"] === "fulfilling") || sameOn(["orderState","fulfillments","shipmentsDelivered","shipmentsFailed","totalCents","txId","cancelReason"])(pre, post),
  },
  { // elicited-by: domain-prior — confirmed by jdubray 2026-07-18T13:39:09.500Z — ledger record: prior:no-charge-without-fraud-pass
    name: "prior:no-charge-without-fraud-pass",
    pred: (pre, action, data, post) => post.txId === pre.txId || (action === 'CHARGE_SUCCEEDED' && pre.orderState === 'charging'),
  },
  { // elicited-by: domain-prior — confirmed by jdubray 2026-07-18T13:39:11.687Z — ledger record: prior:cancel-reason-always-recorded
    name: "prior:cancel-reason-always-recorded",
    pred: (pre, action, data, post) => !['cancelled','rejected'].includes(post.orderState) || post.cancelReason !== '',
  },
  { // elicited-by: designer — confirmed by jdubray 2026-07-18T13:42:38.032Z — ledger record: designer:stale-completions-are-noops
    name: "designer:stale-completions-are-noops",
    pred: (pre, action, data, post) => { const AW = { FRAUD_PASSED: 'fraudCheck', FRAUD_FAILED: 'fraudCheck', CHARGE_SUCCEEDED: 'charging', CHARGE_FAILED: 'charging', CHARGE_TIMED_OUT: 'charging', AMEND_WINDOW_EXPIRED: 'awaitingAmend', SHIPMENT_COMPLETED: 'fulfilling' }; return !(action in AW) || pre.orderState === AW[action] || ['orderState','fulfillments','shipmentsDelivered','shipmentsFailed','totalCents','txId','cancelReason'].every((k) => pre[k] === post[k]); },
  },
];
