// polynv intent ledger — the canonical artifact and system of record
// (docs/polynv-plan.md §8): one record per invariant EVER considered,
// including the abandoned and rejected ones. A plain structured file in git —
// deliberately no database. Append-only at the event level: dispositions,
// pre-checks, and predicate revisions append; nothing is deleted.
//
// Record lifecycle: open → confirmed | rejected | abandoned | superseded.
// 'modify' on any non-superseded record reopens it (a new predicate version
// must earn its own confirmation).
'use strict';

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { compile } from './nf.mjs';

export const LEDGER_FORMAT = 'polynv-ledger/1';
export const OPEN = 'open';
export const TERMINAL_STATUSES = new Set(['confirmed', 'rejected', 'abandoned', 'superseded']);
export const GENERATED_MARKER = '// GENERATED by polynv';

export function loadLedger(path) {
  if (!existsSync(path)) return { format: LEDGER_FORMAT, records: [] };
  const ledger = JSON.parse(readFileSync(path, 'utf-8'));
  if (ledger.format !== LEDGER_FORMAT) {
    throw new Error(`'${path}' has format '${ledger.format}', expected '${LEDGER_FORMAT}' — refusing to guess at a migration`);
  }
  if (!Array.isArray(ledger.records)) throw new Error(`'${path}' has no records array`);
  return ledger;
}

export function saveLedger(path, ledger) {
  writeFileSync(path, JSON.stringify(ledger, null, 2) + '\n');
}

export const findRecord = (ledger, id) => ledger.records.find((r) => r.id === id);

/** The current (last) predicate version of a record, or null (emission-only). */
export const currentVersion = (record) => record.versions.length ? record.versions[record.versions.length - 1] : null;

/**
 * Merge harvested candidates into the ledger as new open records. An id that
 * already exists — in ANY status — is skipped: an abandoned or rejected
 * candidate must never be re-proposed by the next harvest (design decision
 * §10.3), and a confirmed one must not be duplicated.
 */
export function mergeCandidates(ledger, candidates, { date }) {
  const added = [];
  const skipped = [];
  for (const c of candidates) {
    if (findRecord(ledger, c.id)) { skipped.push(c.id); continue; }
    const record = {
      id: c.id,
      source: c.source,
      target: c.target,
      question: c.question,
      evidence: c.evidence ?? null,
      status: OPEN,
      assign: null,
      versions: c.nf ? [{ nf: c.nf, js: c.js, date, author: 'harvest' }] : [],
      precheck: null,
      events: [{ type: 'harvested', date }],
    };
    if (c.provenance) record.provenance = c.provenance; // domain priors: {domain, norm, model, date}
    ledger.records.push(record);
    added.push(record);
  }
  return { added, skipped };
}

/** Add a single hand-raised candidate (domain prior or designer rule). */
export function addCandidate(ledger, { id, source, target, question, js, author, provenance, evidence }, { date }) {
  if (findRecord(ledger, id)) throw new Error(`record '${id}' already exists in the ledger — use \`polynv record --id ${id} --disposition modify\` to revise it`);
  compile({ kind: 'js', target, js }); // parse/shape errors fail HERE, before anything is recorded
  const record = {
    id, source, target, question,
    evidence: evidence ?? null,
    status: OPEN,
    assign: null,
    versions: [{ nf: { kind: 'js', target, js }, js, date, author }],
    precheck: null,
    events: [{ type: 'added', date, author }],
  };
  if (provenance) record.provenance = provenance;
  ledger.records.push(record);
  return record;
}

/**
 * Apply a disposition to a record. Mutates the ledger in memory (caller
 * saves). Rules:
 *   confirm / reject / abandon — only from 'open'. Confirming a temporal
 *     rule additionally requires a graph-checked pre-check (HOLDS/FAILS) —
 *     the report's "graph-checked at elicitation" claim must be true.
 *   defer                     — only from 'open'; records concern/assign.
 *   modify                    — from any status except 'superseded'; appends
 *     a predicate version and REOPENS the record. Temporal records take a
 *     STRUCTURED revision (JSON {"kind":"precedence","first":A,"then":B}),
 *     never free-form js — kind 'js' has no temporal checker, and a rule
 *     that can never be checked must not be recordable (review finding).
 *     `target` (state|transition) may be supplied ONLY for records with no
 *     predicate yet (mutation-survivor questions) to choose the rule shape.
 */
export function applyDisposition(ledger, { id, disposition, author, js, concern, assign, target }, { date }) {
  const record = findRecord(ledger, id);
  if (!record) throw new Error(`no record '${id}' in the ledger`);
  if (!author) throw new Error('--author is required — every disposition is attributed (multi-person elicitation)');
  const event = { type: 'disposition', disposition, date, author };
  if (concern) event.note = concern;

  switch (disposition) {
    case 'confirm':
    case 'reject':
    case 'abandon': {
      if (record.status !== OPEN) throw new Error(`record '${id}' is '${record.status}', not open — use --disposition modify to reopen it with a revised predicate`);
      if (disposition === 'confirm' && !['emission', 'temporal'].includes(record.target) && !currentVersion(record)) {
        throw new Error(`record '${id}' has no predicate to confirm — modify it with --js first`);
      }
      if (disposition === 'confirm' && record.target === 'temporal' && !['HOLDS', 'FAILS'].includes(record.precheck?.verdict)) {
        throw new Error(`record '${id}' has not been graph-checked (pre-check: ${record.precheck?.verdict ?? 'none'}) — a temporal rule is confirmable only after the precedence check ran`);
      }
      record.status = disposition === 'confirm' ? 'confirmed' : disposition === 'reject' ? 'rejected' : 'abandoned';
      break;
    }
    case 'defer': {
      if (record.status !== OPEN) throw new Error(`record '${id}' is '${record.status}', not open — nothing to defer`);
      if (assign) { record.assign = assign; event.assign = assign; }
      break;
    }
    case 'modify': {
      if (record.status === 'superseded') throw new Error(`record '${id}' is superseded — revise its successor instead`);
      if (!js) throw new Error('modify requires --js with the revised predicate');
      if (target !== undefined) {
        // survivor questions carry no predicate and let the ANSWER choose the
        // rule shape; a record with versions keeps its shape forever
        if (record.versions.length) throw new Error(`record '${id}' already has a predicate shape ('${record.target}') — --target only applies to records without one`);
        if (!['state', 'transition'].includes(target)) throw new Error(`--target must be state|transition, got '${target}'`);
        record.target = target;
      }
      if (record.target === 'temporal') {
        // structured revision only — a free-form js temporal rule would be
        // permanently uncheckable (no checker for kind 'js' @ temporal)
        let nf;
        try { nf = JSON.parse(js); } catch { nf = null; }
        if (!nf || nf.kind !== 'precedence' || typeof nf.first !== 'string' || typeof nf.then !== 'string') {
          throw new Error(`temporal records are revised with a structured precedence rule — pass --js '{"kind":"precedence","first":"<ACTION>","then":"<ACTION>"}'`);
        }
        record.versions.push({ nf, js: null, date, author });
      } else {
        const { pred } = compile({ kind: 'js', target: record.target, js }); // push back a non-parsing revision before recording it
        if (record.target === 'state' && pred.length > 1) {
          throw new Error(`a state predicate takes (s) — this one declares ${pred.length} parameters; did you mean --target transition?`);
        }
        record.versions.push({ nf: { kind: 'js', target: record.target, js }, js, date, author });
      }
      record.status = OPEN;
      record.precheck = null; // the old verdict described the old predicate
      break;
    }
    default:
      throw new Error(`unknown disposition '${disposition}' (confirm|reject|abandon|defer|modify)`);
  }
  record.events.push(event);
  return record;
}

/**
 * Content hash of the CONFIRMED rule set — stamped onto the adequacy grade
 * so any later consumer (polyvers' compat-report disclosure) can detect that
 * the invariants changed after grading and refuse to present a stale grade
 * as current (review finding, 2026-07-18).
 */
export function oracleHashOf(ledger) {
  const h = createHash('sha256');
  const confirmed = ledger.records.filter((r) => r.status === 'confirmed').sort((a, b) => a.id.localeCompare(b.id));
  for (const r of confirmed) {
    const v = currentVersion(r);
    h.update(`${r.id} ${v?.js ?? JSON.stringify(v?.nf ?? null)}\n`);
  }
  return h.digest('hex').slice(0, 16);
}

/**
 * Generate invariants.mjs source from the ledger's CONFIRMED records.
 * Confirmed emission-target records are returned in `emissionOnly`
 * (check-effects territory) and temporal ones in `temporalOnly` (graph/
 * monitor territory) — reported, never silently dropped. A confirmed record
 * whose pre-check FAILED still compiles in: the rule IS the intent, and the
 * resulting failing check is the finding, which is the point.
 */
export function generateInvariants(ledger, { helpersSrc }) {
  const confirmed = ledger.records.filter((r) => r.status === 'confirmed');
  const state = [];
  const transition = [];
  const emissionOnly = [];
  const temporalOnly = [];
  for (const r of confirmed) {
    if (r.target === 'emission') { emissionOnly.push(r); continue; }
    if (r.target === 'temporal') { temporalOnly.push(r); continue; }
    const v = currentVersion(r);
    const confirmEvent = [...r.events].reverse().find((e) => e.type === 'disposition' && e.disposition === 'confirm');
    const entry = `  { // elicited-by: ${r.source} — confirmed by ${confirmEvent?.author ?? '?'} ${confirmEvent?.date ?? ''} — ledger record: ${r.id}\n    name: ${JSON.stringify(r.id)},\n    pred: ${v.js},\n  },`;
    (r.target === 'state' ? state : transition).push(entry);
  }
  const uncompiled = [
    emissionOnly.length ? `${emissionOnly.length} emission` : null,
    temporalOnly.length ? `${temporalOnly.length} temporal` : null,
  ].filter(Boolean).join(' + ');
  const code = `${GENERATED_MARKER} from intent-ledger.json — do not edit by hand; revise via \`polynv record --disposition modify\`.
// ${state.length + transition.length} confirmed rule(s)${uncompiled ? ` (+ ${uncompiled} confirmed rule(s) NOT compiled here — see intent-report)` : ''}.
${helpersSrc}

export const stateInvariants = [
${state.join('\n')}
];

export const transitionInvariants = [
${transition.join('\n')}
];
`;
  return { code, count: state.length + transition.length, emissionOnly, temporalOnly };
}
